// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJ_DJm72q7x1m1P8oGtcPsWQuvr8ji0M',
    appId: '1:253481577932:web:14e044f4cd352088eb8169',
    messagingSenderId: '253481577932',
    projectId: 'lablog-d9430',
    authDomain: 'lablog-d9430.firebaseapp.com',
    databaseURL: 'https://lablog-d9430-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lablog-d9430.appspot.com',
    measurementId: 'G-CZ75PV0WGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxEWRPSs2dtPVOLhXVZawnDxnn8NRmLN8',
    appId: '1:253481577932:android:6c771fd358c485d5eb8169',
    messagingSenderId: '253481577932',
    projectId: 'lablog-d9430',
    databaseURL: 'https://lablog-d9430-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lablog-d9430.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaMGQC7XeS9jT7KpXgEsK6b60oi2q9yA',
    appId: '1:253481577932:ios:1b0bb65c17b68f3aeb8169',
    messagingSenderId: '253481577932',
    projectId: 'lablog-d9430',
    databaseURL: 'https://lablog-d9430-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lablog-d9430.appspot.com',
    iosClientId: '253481577932-47lji9nhlt007pkrvk4jm2kovbjqp6cs.apps.googleusercontent.com',
    iosBundleId: 'com.kavarera.labLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMaMGQC7XeS9jT7KpXgEsK6b60oi2q9yA',
    appId: '1:253481577932:ios:1b0bb65c17b68f3aeb8169',
    messagingSenderId: '253481577932',
    projectId: 'lablog-d9430',
    databaseURL: 'https://lablog-d9430-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lablog-d9430.appspot.com',
    iosClientId: '253481577932-47lji9nhlt007pkrvk4jm2kovbjqp6cs.apps.googleusercontent.com',
    iosBundleId: 'com.kavarera.labLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiJ_DJm72q7x1m1P8oGtcPsWQuvr8ji0M',
    appId: '1:253481577932:web:1009f8143b1054c0eb8169',
    messagingSenderId: '253481577932',
    projectId: 'lablog-d9430',
    authDomain: 'lablog-d9430.firebaseapp.com',
    databaseURL: 'https://lablog-d9430-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lablog-d9430.appspot.com',
    measurementId: 'G-MQQWBJFFFX',
  );

}